INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (1,'Thông tin chung','Năm thành lập','2012','Số','Năm','Website Grab','—'),
	 (2,'Thông tin chung','Năm hoạt động tại Việt Nam','2014','Số','Năm','Báo chí, Website Grab','—'),
	 (3,'Thông tin chung','Loại hình doanh nghiệp','Nền tảng công nghệ cung cấp dịch vụ gọi xe và giao hàng','Mô tả','—','Website Grab','—'),
	 (4,'Thông tin chung','Phạm vi hoạt động','Hoạt động tại nhiều tỉnh/thành phố lớn trên toàn quốc','Mô tả','—','Website Grab','—'),
	 (5,'Quy mô','Số lượng tài xế đối tác','Hàng trăm nghìn tài xế đối tác trên toàn quốc','Ước tính','Người','Báo chí, Báo cáo ngành','Không công bố chính xác'),
	 (6,'Quy mô','Số lượng đối tác kinh doanh','Nhà hàng, quán ăn, cửa hàng bán lẻ, siêu thị','Ước tính','Đối tác','Website/App Grab','—'),
	 (7,'Quy mô','Số đơn hàng xử lý','Hàng triệu đơn hàng mỗi ngày tại khu vực Đông Nam Á','Ước tính','Đơn','Báo cáo ngành','—'),
	 (8,'Dịch vụ','Danh mục dịch vụ','GrabBike, GrabCar, GrabFood, GrabExpress','Mô tả','—','Website/App Grab','—'),
	 (9,'Dịch vụ','Thời gian giao hàng','Trung bình 30–60 phút đối với khu vực nội thành','Số/Mô tả','Phút','Ứng dụng Grab','Phụ thuộc khoảng cách'),
	 (10,'Dịch vụ','Theo dõi đơn hàng','Khách hàng theo dõi trạng thái đơn hàng theo thời gian thực (GPS)','Mô tả','—','App Grab','—');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (11,'Giá cước','Phí giao hàng cơ bản','Tính theo quãng đường di chuyển và loại dịch vụ','Số','VNĐ','App Grab','—'),
	 (12,'Giá cước','Phụ phí giờ cao điểm','Áp dụng phụ phí khi nhu cầu tăng cao','Mô tả','—','App Grab','Surge pricing'),
	 (13,'Công nghệ','Nền tảng ứng dụng','Ứng dụng hoạt động trên Android và iOS','Mô tả','—','App Store / Google Play','—'),
	 (14,'Công nghệ','Công nghệ định vị','Ứng dụng công nghệ GPS để định vị và điều phối đơn hàng','Mô tả','—','App Grab','—'),
	 (15,'Công nghệ','Phương thức thanh toán','Tiền mặt, ví điện tử, thẻ ngân hàng','Mô tả','—','App Grab','—'),
	 (16,'Thị trường','Thị phần','Doanh nghiệp có vị thế dẫn đầu thị trường gọi xe và giao hàng tại Việt Nam','Ước tính','—','Báo cáo ngành','Không công bố cụ thể'),
	 (17,'Thương hiệu','Lượt tải ứng dụng','Trên 10 triệu lượt tải tại Việt Nam','Số','Lượt','Google Play','Chỉ số thay thế'),
	 (18,'Truyền thông','Fanpage Facebook','Fanpage chính thức có hàng triệu lượt theo dõi','Số','Người','Facebook','—'),
	 (19,'CSKH','Kênh hỗ trợ khách hàng','Hotline, hỗ trợ trực tuyến qua ứng dụng, email','Mô tả','—','Website/App Grab','—'),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
INSERT INTO public.b (stt,"Nhóm nội dung","Chỉ tiêu thu thập","Nội dung cụ thể ( Be )","Dạng dữ liệu","Đơn vị","Nguồn dữ liệu","Ghi chú") VALUES
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','',''),
	 (NULL,'','','','','','','');
